### ISSUE TITLE
Use relative urls

### ISSUE THREAD

**Issue by kobybr** [codingchili/excelastic#66]
Would like to see relative urls instead of absolute so this app can be used with reverse proxies (Apache ProxyPass/ProxyPassReverse)

i.e.  href='../static/css/bootstrap.min.css' versus href='/static/css/bootstrap.min.css'

or allow for a base path to be set in the configuration file

**Comment by codingchili** [comment]
Hello,

Yes of course, this is a simple fix.
I'll make sure its included in the next release, at the end of this week.

Thanks for submitting an issue.

**Comment by codingchili** [comment]
Fixed in 1.3.3 - now using relative paths for forms, resources and websocket. Please remember to forward the websocket through the reverse proxy - it's on the same port as the website.

Let me know if I missed something.

**Comment by kobybr** [comment]
Thanks for the change.   However, I'm still seeing the paths as absolute.   Here is a similar issue from another project that might help explain what I am experiencing.  https://github.com/lmenezes/cerebro/issues/98

**Comment by codingchili** [comment]
Aha, I see. I'll check it. Reopening.

**Comment by kobybr** [comment]
Hi Robin.  

Just checking in on this and wondering if you had a time frame for implementation.   

Thanks for your help!

**Comment by codingchili** [comment]
Hi kobybr,

No time frame yet, it's one of the prioritized issues I will be working on - the next time I have some budget available for this project :)

BR
